// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: tracker/v1/tracker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tracking struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeopleId int32  `protobuf:"varint,1,opt,name=people_id,json=peopleId,proto3" json:"people_id,omitempty"`
	SourceId int32  `protobuf:"varint,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	UrlId    *int32 `protobuf:"varint,3,opt,name=url_id,json=urlId,proto3,oneof" json:"url_id,omitempty"`
}

func (x *Tracking) Reset() {
	*x = Tracking{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracker_v1_tracker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tracking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracking) ProtoMessage() {}

func (x *Tracking) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_v1_tracker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracking.ProtoReflect.Descriptor instead.
func (*Tracking) Descriptor() ([]byte, []int) {
	return file_tracker_v1_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *Tracking) GetPeopleId() int32 {
	if x != nil {
		return x.PeopleId
	}
	return 0
}

func (x *Tracking) GetSourceId() int32 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *Tracking) GetUrlId() int32 {
	if x != nil && x.UrlId != nil {
		return *x.UrlId
	}
	return 0
}

var File_tracker_v1_tracker_proto protoreflect.FileDescriptor

var file_tracker_v1_tracker_proto_rawDesc = []byte{
	0x0a, 0x18, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x65, 0x72, 0x22, 0x6b, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x06, 0x75, 0x72, 0x6c,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x05, 0x75, 0x72, 0x6c,
	0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x75, 0x72, 0x6c, 0x5f, 0x69, 0x64,
	0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x76, 0x31,
	0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tracker_v1_tracker_proto_rawDescOnce sync.Once
	file_tracker_v1_tracker_proto_rawDescData = file_tracker_v1_tracker_proto_rawDesc
)

func file_tracker_v1_tracker_proto_rawDescGZIP() []byte {
	file_tracker_v1_tracker_proto_rawDescOnce.Do(func() {
		file_tracker_v1_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(file_tracker_v1_tracker_proto_rawDescData)
	})
	return file_tracker_v1_tracker_proto_rawDescData
}

var file_tracker_v1_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tracker_v1_tracker_proto_goTypes = []interface{}{
	(*Tracking)(nil), // 0: tracker.Tracking
}
var file_tracker_v1_tracker_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tracker_v1_tracker_proto_init() }
func file_tracker_v1_tracker_proto_init() {
	if File_tracker_v1_tracker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tracker_v1_tracker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tracking); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_tracker_v1_tracker_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tracker_v1_tracker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tracker_v1_tracker_proto_goTypes,
		DependencyIndexes: file_tracker_v1_tracker_proto_depIdxs,
		MessageInfos:      file_tracker_v1_tracker_proto_msgTypes,
	}.Build()
	File_tracker_v1_tracker_proto = out.File
	file_tracker_v1_tracker_proto_rawDesc = nil
	file_tracker_v1_tracker_proto_goTypes = nil
	file_tracker_v1_tracker_proto_depIdxs = nil
}
